services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build: ./back-end
    ports:
      - "4000:4000"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
